import type { Metadata } from "next";
import "./globals.css";
import { Fira_Code } from "next/font/google";

//Components
import Header from "@/components/Header";

export const geistFira = Fira_Code({
  variable: "--font-geist-fira",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col ${geistFira.variable} pb-4 font-primary text-zinc-500 container mx-auto `}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
